### ISSUE TITLE
Not a bug! But a request - Could you please include an explanation on how to run this web app on a Docker container?

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [neonexus/sails-react-bootstrap-webpack#58]
I used your `Dockerfile` to deploy the app for development in Docker Desktop. I was able to deploy the app for development successfully. Thank you!

But I tried to do the same for production, I couldn't deploy successfully. Couldn't make sure what needs to be changed!

It would be of great help if you could include an explanation on how to run this web app on a Docker container for PRODUCTION in README.

Thanks

**Comment by neonexus** [comment]
`NODE_ENV=production` part of the final Docker instruction already forces Sails into a production environment (See [line 23 of the Dockerfile](https://github.com/neonexus/sails-react-bootstrap-webpack/blob/release/Dockerfile#L23)). So, I don't know how to help you, because either you are confusing what is going on with Sails and environments, or not fully understanding how your deployment environment works...
