### ISSUE TITLE
React Strict Mode and Session Cookie

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [neonexus/sails-react-bootstrap-webpack#66]
Hi,

I'm using your starter pack for my app.

I have a function which makes API call like below

```
    // Fetch the tasks of `workflowDescription` from DB
    const fetchWorkflowTasks = async () => {
        return new Promise(function (resolve, reject) {
            props.api.post({
                url: '/fetchWorkflowTasks',
                body: {
                    workflowDescription: props.workloadDetails.Description,
                }
            }, (res) => {
                if (res.tasks) {
                    handleWorkflowTasks(res.tasks);
                    resolve(res.tasks);
                }
            }, (err, resp) => {
                reject('Oops! Couldn\'t fetch tasks from DB.');
            });
        });
    }
```

In **React strict mode**, the call properly returns the required data from the Sails backend. But immediately after that, API error occurs throwing `You are not logged in` from `isLoggedIn.js`.

If I disable strict mode, there is no issue. I'm not sure what's the issue and how to debug!?

Could you please guide me on this? Thanks.

**Comment by neonexus** [comment]
Only thing I think of to help debug this, would be to check out the `RequestLog` model data (custom to this repo / start kit). This would give you some insight into what is going on with your API calls at least. I built the [api/hooks/request-logger.js](https://github.com/neonexus/sails-react-bootstrap-webpack/blob/release/api/hooks/request-logger.js), [api/models/RequestLog.js](https://github.com/neonexus/sails-react-bootstrap-webpack/blob/release/api/models/RequestLog.js), and [api/helpers/finalize-request-log.js](https://github.com/neonexus/sails-react-bootstrap-webpack/blob/release/api/helpers/finalize-request-log.js), to help with issues just like this.

Another idea that comes to mind; CSRF protection I built forces modification requests (POST / PUT / DELETE) to be serial, and can't be parallel, because the CSRF token is single-use, and rotates after each use. I did not build it to handle parallel requests per session. GET requests can be parallel, as they don't spend CSRF tokens. It is possible parallel requests are being made, and if so, would cause this kind of issue, as the system is designed to log the user out if they give a bad CSRF token.

**Comment by MaheshkumarSundaram** [comment]
Thank you for your apt response.

I checked the `RequestLog`. The issue seems to be due to parallel requests because when using Strict mode, my POST API call is called twice (using the same CSRF token) due to the rerendering.

**Comment by neonexus** [comment]
Ah, sounds like you need a rerender blocker (at least, that's what I call it). The way I implement this, is I set an initial state variable in the constructor (something like `this.state.hasLoaded`) to `false`, wrapping all of the contents of `render()` in an `if` statement, returning `null` if loading is still going. Then, after I've made whatever API calls, or setup of whatever, I update the state variable to `true`, forcing a rerender when I want it, not when React does.

**Comment by MaheshkumarSundaram** [comment]
Yeah. Exactly. That's what I am doing now to get rid of the issue. Thanks for your help. Much appreciated.

**Comment by neonexus** [comment]
Glad I could help, and glad you are finding my repo useful! It only took me about 20 something-ish years to build it XD (I've been learning how to program for 20+ years, 10 years professionally). A lot of things I found myself repeating over the years has been distilled into this repo (and the little npm repo [[fixted](https://www.npmjs.com/package/fixted)] I took over to help test Sails).

There are still things I'm working on, to make the demo a bit better. So, keep an eye out.

**Comment by neonexus** [comment]
I'm always open to some help @MaheshkumarSundaram. I just commited a bunch of work I've been doing to `master`.  The most notable update is the PwnedPasswords.com API integration (HaveIBeenPwned.com). Well worth a look, and I'll make it a release soon.

**Comment by MaheshkumarSundaram** [comment]
Hi @neonexus,

Thanks for your update. I'll check that out.

One more request. Could you please open the `Discussion` tab for the project?
It would be very useful to have conversations regarding development instead of raising **issues**. 
Thank you!

**Comment by MaheshkumarSundaram** [comment]
> I'm always open to some help @MaheshkumarSundaram. I just commited a bunch of work I've been doing to `master`. The most notable update is the PwnedPasswords.com API integration (HaveIBeenPwned.com). Well worth a look, and I'll make it a release soon. [be8fc13#diff-76587a1ff3ab9997f53a0c19016f6dd4e2dbe76ed7307b99e577947419c4c5bdR39](https://github.com/neonexus/sails-react-bootstrap-webpack/commit/be8fc139b12d41699bf225e9ec9bac59fff1a07a#diff-76587a1ff3ab9997f53a0c19016f6dd4e2dbe76ed7307b99e577947419c4c5bdR39)

Hi @neonexus,

I checked out your PwnedPasswords.com API integration in your `master` branch. It's an elegant and clear functionality. Nice work and concisely done! :tada::tada::tada:

**Comment by neonexus** [comment]
@MaheshkumarSundaram Thanks! I always strive for the most straightforward way of building something. The less comments I have to make, to make the code understandable, the better.
